-- cú pháp thêm khóa ngoại ngay khi tạo bảng:
-- FOREIGN KEY (MAHLV) REFERENCES HUANLUYENVIEN(MAHLV),

ALTER TABLE TRANDAU
ADD
    FOREIGN KEY (MACLB1) REFERENCES CAULACBO(MACLB),
    FOREIGN KEY (MACLB2) REFERENCES CAULACBO(MACLB),
    FOREIGN KEY (MASAN) REFERENCES SANVD(MASAN)

ALTER TABLE BANGXH
ADD
    FOREIGN KEY (MACLB) REFERENCES CAULACBO(MACLB)

ALTER TABLE CAULACBO
ADD
    FOREIGN KEY (MASAN) REFERENCES SANVD(MASAN),
    FOREIGN KEY (MATINH) REFERENCES TINH(MATINH)

ALTER TABLE CAUTHU
ADD
    FOREIGN KEY (MACLB) REFERENCES CAULACBO(MACLB),
    FOREIGN KEY (MAQG) REFERENCES QUOCGIA(MAQG)

ALTER TABLE HUANLUYENVIEN
ADD
    FOREIGN KEY (MAQG) REFERENCES QUOCGIA(MAQG)

ALTER TABLE HLV_CLB
ADD
    FOREIGN KEY (MAHLV) REFERENCES HUANLUYENVIEN(MAHLV),
    FOREIGN KEY (MACLB) REFERENCES CAULACBO(MACLB)
