SELECT NGAYTD, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD
LEFT JOIN CAULACBO CLB1 ON TD.MACLB1=CLB1.MACLB
LEFT JOIN CAULACBO CLB2 ON TD.MACLB2=CLB2.MACLB
WHERE MONTH(NGAYTD)=3
    AND (
            (
            TD.MASAN IN (
                SELECT MASAN
                FROM CAULACBO
                WHERE MACLB=MACLB1)
            AND SUBSTRING(KETQUA, 3, 1)='0'
            )
        OR (
            TD.MASAN IN (
                SELECT MASAN
                FROM CAULACBO
                WHERE MACLB=MACLB2)
            AND SUBSTRING(KETQUA, 1, 1)='0'
            )
    )

-- test
SELECT *
FROM TRANDAU TD
LEFT JOIN CAULACBO CLB1 ON TD.MACLB1=CLB1.MACLB
LEFT JOIN CAULACBO CLB2 ON TD.MACLB2=CLB2.MACLB
WHERE MONTH(NGAYTD)=3