SELECT TENCLB
FROM CAULACBO
WHERE MACLB IN (
    SELECT MACLB
    FROM HLV_CLB
    WHERE MAHLV IN (
        SELECT MAHLV
        FROM HUANLUYENVIEN
        WHERE DATEDIFF(day, NGAYSINH, '8/20/2019')=0
    ) AND VAITRO=N'HLV Chính'
)

-- test
SELECT TENCLB
FROM CAULACBO
WHERE MACLB IN (
    SELECT MACLB
    FROM HLV_CLB
    WHERE MAHLV IN (
        SELECT MAHLV
        FROM HUANLUYENVIEN
        WHERE DATEDIFF(day, NGAYSINH, '05/20/1972')=0
    ) AND VAITRO=N'HLV Chính'
)