SELECT CLB.MACLB, TENCLB, TENSAN, SANVD.DIACHI,
    COUNT(DISTINCT MACT) AS SOCTNUOCNGOAI
FROM CAUTHU CT
    LEFT JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
    LEFT JOIN SANVD ON CLB.MASAN = SANVD.MASAN
WHERE MAQG != 'VN'
GROUP BY CLB.MACLB, TENSAN, TENCLB, SANVD.DIACHI