WITH MACLBHANGTHAPNHAT (VONG3NAM2009) AS (
    SELECT MACLB
    FROM BANGXH
    WHERE VONG=3 AND NAM=2009
        AND HANG = (
            SELECT MAX(HANG)
            FROM BANGXH
            WHERE VONG=3 AND NAM=2009
        )
)

SELECT NGAYTD, TENSAN, 
    CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD
    LEFT JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
    LEFT JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
    LEFT JOIN SANVD ON TD.MASAN = SANVD.MASAN
WHERE CLB1.MACLB IN (SELECT VONG3NAM2009 FROM MACLBHANGTHAPNHAT)
    OR CLB2.MACLB IN (SELECT VONG3NAM2009 FROM MACLBHANGTHAPNHAT)

