WITH THEMDOINGUOC (MACLB1, MACLB2) AS (
    SELECT MACLB1, MACLB2
    FROM TRANDAU
    UNION
    SELECT MACLB2, MACLB1
    FROM TRANDAU
)

SELECT MACLB, TENCLB
FROM CAULACBO
WHERE MACLB IN (
    SELECT MACLB1
    FROM THEMDOINGUOC
    GROUP BY MACLB1
    HAVING COUNT(DISTINCT MACLB2) = (
        SELECT COUNT(DISTINCT MACLB) FROM CAULACBO) - 1
);

-- test
WITH THEMDOINGUOC (MACLB1, MACLB2) AS (
    SELECT MACLB1, MACLB2
    FROM TRANDAU
    UNION
    SELECT MACLB2, MACLB1
    FROM TRANDAU
)

SELECT MACLB1, COUNT(DISTINCT MACLB2) AS SODOITHUDISTINCT
FROM THEMDOINGUOC
GROUP BY MACLB1;


WITH THEMDOINGUOC (MACLB1, MACLB2) AS (
    SELECT MACLB1, MACLB2
    FROM TRANDAU
    UNION
    SELECT MACLB2, MACLB1
    FROM TRANDAU
),
TESTCAULACBO AS (
    SELECT *
    FROM CAULACBO
    WHERE MACLB != 'HAGL'
)

SELECT MACLB, TENCLB
FROM TESTCAULACBO
WHERE MACLB IN (
    SELECT MACLB1
    FROM THEMDOINGUOC
    GROUP BY MACLB1
    HAVING COUNT(DISTINCT MACLB2) = (
        SELECT COUNT(DISTINCT MACLB) FROM TESTCAULACBO) - 1
);