DROP VIEW IF EXISTS D1

GO
CREATE VIEW D1 AS
SELECT MACT, SO, HOTEN, NGAYSINH, DIACHI, VITRI
FROM CAUTHU
WHERE MACLB IN (
    SELECT MACLB
    FROM CAULACBO
    WHERE TENCLB=N'SHB ĐÀ NẴNG'
) AND MAQG IN (
    SELECT MAQG
    FROM QUOCGIA
    WHERE TENQG=N'Bra-xin')
GO

SELECT *
FROM D1