DROP VIEW IF EXISTS D12

GO
CREATE VIEW D12 AS
WITH MACLBXHCAONHAT (VONG3NAM2009) AS (
    SELECT MACLB
    FROM BANGXH
    WHERE HANG=1 AND VONG=3 AND NAM=2009
)
SELECT NGAYTD, TENSAN,
    CLB1.TENCLB TENCLB1, CLB2.TENCLB TENCLB2, KETQUA
FROM TRANDAU TD
    LEFT JOIN SANVD ON TD.MASAN = SANVD.MASAN
    LEFT JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
    LEFT JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE
    CLB1.MACLB IN (SELECT VONG3NAM2009 FROM MACLBXHCAONHAT)
    OR CLB2.MACLB IN (SELECT VONG3NAM2009 FROM MACLBXHCAONHAT)
GO

SELECT *
FROM D12

-- test
SELECT *
FROM BANGXH
WHERE VONG=3 AND NAM=2009

SELECT *
FROM TRANDAU