DROP VIEW IF EXISTS D13

GO
CREATE VIEW D13 AS
WITH MACLBXHTHAPNHAT (VONG3NAM2009) AS (
    SELECT MACLB
    FROM BANGXH
    WHERE HANG=(
        SELECT MAX(HANG)
        FROM BANGXH
        WHERE VONG=3 AND NAM=2009
    ) AND VONG=3 AND NAM=2009
)
SELECT NGAYTD, TENSAN,
    CLB1.TENCLB TENCLB1, CLB2.TENCLB TENCLB2, KETQUA
FROM TRANDAU TD
    LEFT JOIN SANVD ON TD.MASAN = SANVD.MASAN
    LEFT JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
    LEFT JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE
    CLB1.MACLB IN (SELECT VONG3NAM2009 FROM MACLBXHTHAPNHAT)
    OR CLB2.MACLB IN (SELECT VONG3NAM2009 FROM MACLBXHTHAPNHAT)
GO

SELECT *
FROM D13

-- test
SELECT *
FROM BANGXH
WHERE VONG=3 AND NAM=2009

SELECT *
FROM TRANDAU
