DROP VIEW IF EXISTS D2

GO
CREATE VIEW D2 AS
SELECT MATRAN, NGAYTD, TENSAN,
    CLB1.TENCLB TENCLB1, CLB2.TENCLB TENCLB2, KETQUA
FROM TRANDAU TD
    LEFT JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
    LEFT JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
    LEFT JOIN SANVD ON TD.MASAN = SANVD.MASAN
WHERE VONG=3 AND NAM=2009
GO

SELECT *
FROM D2