DROP VIEW IF EXISTS D3

GO
CREATE VIEW D3 AS
SELECT HLV_CLB.MAHLV, TENHLV, NGAYSINH, DIACHI, VAITRO, TENCLB
FROM HLV_CLB
    LEFT JOIN HUANLUYENVIEN HLV ON HLV_CLB.MAHLV = HLV.MAHLV
    LEFT JOIN CAULACBO CLB ON HLV_CLB.MACLB = CLB.MACLB
WHERE MAQG IN (
    SELECT MAQG
    FROM QUOCGIA
    WHERE TENQG=N'Việt Nam'
)
GO 

SELECT *
FROM D3