DROP VIEW IF EXISTS D5

GO
CREATE VIEW D5 AS
SELECT TENTINH, COUNT(DISTINCT MACT) AS SOCTTIENDAO
FROM CAUTHU CT
    LEFT JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
    LEFT JOIN TINH ON CLB.MATINH = TINH.MATINH
WHERE VITRI = N'Tiền đạo'
GROUP BY TINH.MATINH, TENTINH
GO

SELECT *
FROM D5