DROP VIEW IF EXISTS D6

GO
CREATE VIEW D6 AS
SELECT TENCLB, TENTINH
FROM CAULACBO CLB
    LEFT JOIN TINH ON CLB.MATINH = TINH.MATINH
WHERE MACLB IN (
    SELECT MACLB
    FROM BANGXH
    WHERE VONG=3 AND NAM=2009 AND HANG=1
)
GO

SELECT *
FROM D6

-- test 
SELECT *
FROM BANGXH
WHERE VONG=3 AND NAM=2009