DROP VIEW IF EXISTS D7

GO
CREATE VIEW D7 AS
SELECT TENHLV
FROM HLV_CLB
    LEFT JOIN HUANLUYENVIEN HLV ON HLV_CLB.MAHLV = HLV.MAHLV
WHERE DIENTHOAI IS NULL
GO

SELECT *
FROM D7

-- test
UPDATE HUANLUYENVIEN
SET DIENTHOAI = NULL
WHERE MAHLV = 'HLV05'

SELECT *
FROM D7

UPDATE HUANLUYENVIEN
SET DIENTHOAI = '0909099990'
WHERE MAHLV = 'HLV05'