DROP VIEW IF EXISTS D8

GO
CREATE VIEW D8 AS
SELECT HLV.*
FROM HUANLUYENVIEN HLV
WHERE MAHLV NOT IN (
    SELECT MAHLV
    FROM HLV_CLB
) AND MAQG IN (
    SELECT MAQG
    FROM QUOCGIA
    WHERE TENQG=N'Việt Nam'
)
GO

SELECT *
FROM D8

-- test
INSERT INTO HUANLUYENVIEN
VALUES ('HLV07', N'Tên Test', '11/23/1998', NULL, NULL, 'VN')

SELECT *
FROM D8

DELETE FROM HUANLUYENVIEN
WHERE MAHLV = 'HLV07'