CREATE OR ALTER TRIGGER B2
ON CAUTHU
INSTEAD OF INSERT
AS
BEGIN
    INSERT INTO CAUTHU (HOTEN, VITRI, NGAYSINH, DIACHI, MACLB, MAQG, SO)
    SELECT HOTEN, VITRI, NGAYSINH, DIACHI, MACLB, MAQG, SO
    FROM inserted

    IF EXISTS (
        SELECT MACLB, COUNT(DISTINCT MACT), COUNT(DISTINCT SO)
        FROM CAUTHU
        GROUP BY MACLB
        HAVING COUNT(DISTINCT MACT) != COUNT(DISTINCT SO)
    )
    BEGIN
        RAISERROR(N'Có cầu thủ trùng số', 16, 0)
        ROLLBACK
    END
END
GO


-- test 
INSERT INTO CAUTHU
VALUES (N'Nguyễn Văn A Test', N'Tiền đạo', '8/14/2000', NULL, 'HAGL', 'VN', 6)

DELETE FROM CAUTHU
WHERE HOTEN = N'Nguyễn Văn A Test'

-- error here
INSERT INTO CAUTHU
VALUES (N'Nguyễn Văn A Test', N'Tiền đạo', '8/14/2000', NULL, 'HAGL', 'VN', 3) 

-- delete trigger
GO
DROP TRIGGER B2
GO