SELECT *
FROM CAUTHU
WHERE MACLB IN (
    SELECT MACLB
    FROM CAULACBO
    WHERE MASAN IN (
        SELECT MASAN
        FROM SANVD
        WHERE TENSAN=N'Long An'))

-- test:
SELECT *
FROM CAUTHU
WHERE MACLB IN (
    SELECT MACLB
    FROM CAULACBO
    WHERE MASAN IN (
        SELECT MASAN
        FROM SANVD
        WHERE TENSAN IN (N'Pleiku', N'Gò Đậu')))