SELECT MATRAN, NGAYTD, TENSAN,
    CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU, SANVD,
    CAULACBO AS CLB1, CAULACBO AS CLB2
WHERE TRANDAU.MASAN=SANVD.MASAN
    AND TRANDAU.MACLB1=CLB1.MACLB
    AND TRANDAU.MACLB2=CLB2.MACLB
    AND VONG=2
    AND NAM=2009

-- so sánh với:
SELECT *
FROM TRANDAU
WHERE VONG=2 AND NAM=2009