SELECT MACLB, COUNT(DISTINCT MACT) AS SOCAUTHU
FROM CAUTHU
GROUP BY MACLB

-- thêm tên clb
SELECT CAUTHU.MACLB, TENCLB, COUNT(DISTINCT MACT) AS SOCAUTHU
FROM CAUTHU, CAULACBO
WHERE CAUTHU.MACLB = CAULACBO.MACLB
GROUP BY CAUTHU.MACLB, TENCLB