SELECT MACLB, COUNT(DISTINCT MACT) AS SOCAUTHUNUOCNGOAI
FROM CAUTHU
WHERE MAQG NOT IN (
    SELECT MAQG
    FROM QUOCGIA
    WHERE TENQG=N'Việt Nam')
GROUP BY MACLB

-- thêm tên clb, và một cách viết khác của lệnh where
SELECT CAUTHU.MACLB, TENCLB, COUNT(DISTINCT MACT) AS SOCAUTHUNUOCNGOAI
FROM CAUTHU, CAULACBO
WHERE CAUTHU.MACLB = CAULACBO.MACLB
    AND MAQG IN (
        SELECT MAQG
        FROM QUOCGIA
        WHERE TENQG!=N'Việt Nam')
GROUP BY CAUTHU.MACLB, TENCLB