SELECT TENTINH, COUNT (DISTINCT MACT) AS SOCAUTHUTIENDAO
FROM CAUTHU, CAULACBO, TINH
WHERE CAUTHU.MACLB=CAULACBO.MACLB
    AND CAULACBO.MATINH=TINH.MATINH
    AND VITRI=N'Tiền đạo'
GROUP BY TENTINH

-- test tất cả vị trí
SELECT VITRI, TENTINH, COUNT (DISTINCT MACT) AS SOCAUTHU
FROM CAUTHU, CAULACBO, TINH
WHERE CAUTHU.MACLB=CAULACBO.MACLB
    AND CAULACBO.MATINH=TINH.MATINH
GROUP BY VITRI, TENTINH