SELECT TOP 1 TENCLB, TENTINH
FROM CAULACBO, TINH, BANGXH
WHERE CAULACBO.MATINH=TINH.MATINH
    AND CAULACBO.MACLB=BANGXH.MACLB
    AND VONG=3
    AND NAM=2009
ORDER BY HANG ASC

-- or HANG=1
-- test
SELECT *
FROM CAULACBO, TINH, BANGXH
WHERE CAULACBO.MATINH=TINH.MATINH
    AND CAULACBO.MACLB=BANGXH.MACLB
    AND VONG=3
    AND NAM=2009
ORDER BY HANG ASC