SELECT TENHLV
FROM HUANLUYENVIEN, HLV_CLB
WHERE HUANLUYENVIEN.MAHLV=HLV_CLB.MAHLV
    AND DIENTHOAI IS NULL

-- test
INSERT INTO HUANLUYENVIEN
VALUES ('HLVT', 'HLV Test', '2003-12-31', N'165 Chùa Bộc', NULL, 'VN')

INSERT INTO HLV_CLB
VALUES ('HLVT', 'BBD', 'HLV Bù nhìn')

SELECT TENHLV
FROM HUANLUYENVIEN, HLV_CLB
WHERE HUANLUYENVIEN.MAHLV=HLV_CLB.MAHLV
    AND DIENTHOAI IS NULL

SELECT *
FROM HUANLUYENVIEN, HLV_CLB
WHERE HUANLUYENVIEN.MAHLV=HLV_CLB.MAHLV

DELETE FROM HLV_CLB
WHERE MAHLV='HLVT'

DELETE FROM HUANLUYENVIEN
WHERE MAHLV='HLVT'

