SELECT HUANLUYENVIEN.*
FROM HUANLUYENVIEN
WHERE HUANLUYENVIEN.MAHLV NOT IN (
    SELECT MAHLV
    FROM HLV_CLB
)

-- test
INSERT INTO HUANLUYENVIEN
VALUES ('HLVT', 'HLV Test', '2003-12-31', N'165 Chùa Bộc', NULL, 'VN')

SELECT HUANLUYENVIEN.*
FROM HUANLUYENVIEN
WHERE HUANLUYENVIEN.MAHLV NOT IN (
    SELECT MAHLV
    FROM HLV_CLB
)

DELETE FROM HUANLUYENVIEN
WHERE MAHLV='HLVT'