SELECT CAUTHU.*
FROM CAUTHU, CAULACBO, BANGXH
WHERE CAUTHU.MACLB=CAULACBO.MACLB
    AND CAULACBO.MACLB=BANGXH.MACLB
    AND VONG=3
    AND NAM=2009
    AND (HANG>6 OR HANG<3)

-- test
SELECT * 
FROM BANGXH
WHERE VONG=3
    AND NAM=2009

SELECT *
FROM CAUTHU, CAULACBO, BANGXH
WHERE CAUTHU.MACLB=CAULACBO.MACLB
    AND CAULACBO.MACLB=BANGXH.MACLB
    AND VONG=3
    AND NAM=2009

