SELECT NGAYTD, TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU, CAULACBO AS CLB1, CAULACBO AS CLB2, SANVD
WHERE TRANDAU.MACLB1=CLB1.MACLB
    AND TRANDAU.MACLB2=CLB2.MACLB
    AND TRANDAU.MASAN=SANVD.MASAN
    AND (
        CLB1.MACLB IN (
            SELECT MACLB
            FROM BANGXH
            WHERE VONG=3 AND HANG=1)
    OR
        CLB2.MACLB IN (
            SELECT MACLB
            FROM BANGXH
            WHERE VONG=3 AND HANG=1))

-- test
SELECT *
FROM TRANDAU, CAULACBO AS CLB1, CAULACBO AS CLB2, SANVD
WHERE TRANDAU.MACLB1=CLB1.MACLB
    AND TRANDAU.MACLB2=CLB2.MACLB
    AND TRANDAU.MASAN=SANVD.MASAN
    AND (
        CLB1.MACLB IN (
        SELECT MACLB
        FROM BANGXH
        WHERE VONG=3 AND HANG=1)
    OR
        CLB2.MACLB IN (
        SELECT MACLB
        FROM BANGXH
        WHERE VONG=3 AND HANG=1))

